// Extra names and demonyms used to geo-tag headlines. Country names themselves
// come from i18n-iso-countries; this adds how the news actually refers to places.
// Matching is case-sensitive on word boundaries. Ambiguous words that are also
// common English words or first names are deliberately left out (e.g. "Chad",
// "Jordan", "Georgia", "Turkey", "China" as in porcelain is fine because it's capitalised).
export const COUNTRY_TERMS: Record<string, string[]> = {
  AFG: ['Afghan', 'Afghans', 'Kabul', 'Taliban'],
  ARE: ['UAE', 'Emirati', 'Abu Dhabi', 'Dubai'],
  ARG: ['Argentine', 'Argentinian', 'Buenos Aires'],
  ARM: ['Armenian', 'Yerevan'],
  AUS: ['Australian', 'Canberra'],
  AZE: ['Azerbaijani', 'Baku'],
  BGD: ['Bangladeshi', 'Dhaka'],
  BLR: ['Belarusian', 'Minsk', 'Lukashenko'],
  BRA: ['Brazilian', 'Brasilia', 'Brasília'],
  CAN: ['Canadian', 'Ottawa'],
  CHN: ['Chinese', 'Beijing', 'PLA', 'Xi Jinping'],
  COD: ['DR Congo', 'DRC', 'Congolese', 'Kinshasa', 'Goma'],
  COL: ['Colombian', 'Bogota', 'Bogotá'],
  CUB: ['Cuban', 'Havana'],
  DEU: ['German', 'Berlin', 'Bundeswehr'],
  EGY: ['Egyptian', 'Cairo'],
  ESP: ['Spanish', 'Madrid'],
  ETH: ['Ethiopian', 'Addis Ababa', 'Tigray', 'Amhara'],
  FRA: ['French', 'Paris', 'Élysée', 'Elysee'],
  GBR: ['UK', 'British', 'Britain', 'London', 'Downing Street', 'Westminster'],
  GRC: ['Greek', 'Athens'],
  HTI: ['Haitian', 'Port-au-Prince'],
  IDN: ['Indonesian', 'Jakarta'],
  IND: ['Indian', 'New Delhi', 'Delhi', 'Kashmir'],
  IRN: ['Iranian', 'Tehran', 'IRGC'],
  IRQ: ['Iraqi', 'Baghdad', 'Kurdistan Region', 'Erbil'],
  ISR: ['Israeli', 'Jerusalem', 'Tel Aviv', 'IDF', 'Netanyahu'],
  ITA: ['Italian', 'Rome'],
  JPN: ['Japanese', 'Tokyo'],
  KAZ: ['Kazakh', 'Astana'],
  KEN: ['Kenyan', 'Nairobi'],
  KOR: ['South Korean', 'Seoul'],
  PRK: ['North Korean', 'Pyongyang', 'DPRK', 'Kim Jong Un'],
  LBN: ['Lebanese', 'Beirut', 'Hezbollah'],
  LBY: ['Libyan', 'Tripoli', 'Benghazi'],
  MEX: ['Mexican', 'Mexico City'],
  MLI: ['Malian', 'Bamako'],
  MMR: ['Burmese', 'Myanmar', 'Naypyidaw', 'Yangon', 'Rakhine'],
  NER: ['Nigerien', 'Niamey'],
  NGA: ['Nigerian', 'Abuja', 'Lagos'],
  PAK: ['Pakistani', 'Islamabad', 'Karachi', 'Lahore'],
  PHL: ['Philippine', 'Filipino', 'Manila'],
  POL: ['Polish', 'Warsaw'],
  PSE: ['Palestinian', 'Palestinians', 'Gaza', 'West Bank', 'Hamas', 'Ramallah'],
  QAT: ['Qatari', 'Doha'],
  ROU: ['Romanian', 'Bucharest'],
  RUS: ['Russian', 'Russians', 'Moscow', 'Kremlin', 'Putin'],
  SAU: ['Saudi', 'Riyadh'],
  SDN: ['Sudanese', 'Khartoum', 'Darfur', 'RSF', 'El Fasher'],
  SOM: ['Somali', 'Mogadishu', 'al-Shabab', 'Al-Shabaab'],
  SRB: ['Serbian', 'Belgrade'],
  SSD: ['South Sudanese', 'Juba'],
  SYR: ['Syrian', 'Damascus', 'Aleppo', 'Idlib'],
  THA: ['Thai', 'Bangkok'],
  TUR: ['Turkish', 'Türkiye', 'Turkiye', 'Ankara', 'Istanbul', 'Erdogan', 'Erdoğan'],
  TWN: ['Taiwanese', 'Taipei'],
  UKR: ['Ukrainian', 'Ukrainians', 'Kyiv', 'Kiev', 'Kharkiv', 'Odesa', 'Zelensky', 'Zelenskyy', 'Donbas', 'Crimea'],
  USA: ['US', 'U.S.', 'American', 'Americans', 'Washington', 'White House', 'Pentagon'],
  VEN: ['Venezuelan', 'Caracas', 'Maduro'],
  VNM: ['Vietnamese', 'Hanoi'],
  YEM: ['Yemeni', 'Sanaa', "Sana'a", 'Houthi', 'Houthis', 'Aden'],
  ZAF: ['South African', 'Pretoria', 'Johannesburg'],
};

/** Official short names that are also everyday words — never matched on their own. */
export const AMBIGUOUS_NAMES = new Set(['Chad', 'Jordan', 'Georgia', 'Turkey', 'Guinea', 'Niger', 'Dominica', 'Togo']);
